# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DFPAdapterDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DFPAdapterDemo
	pod 'BlueStackDFPMediationAdapter'
	pod 'Google-Mobile-Ads-SDK'


end
