    
platform :ios, '12.2'

use_frameworks!
#load 'BlueStackDuplicatedFrameworksRemover.rb'

def common_pods


    #BlueStack
    pod "BlueStack-SDK", '4.2.6'
    pod "MAdvertiseCMP" ,'64'
  
end

target 'DemoSwift' do
  common_pods
end
#post_install do |installer|
#    remove_duplicated_frameworks('Pods-DemoSwift', installer)
#end
