source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.2'

target 'MNG-Ads-SDK-Demo' do
  
   pod 'MAdvertiseCMP' ,'64'
   pod 'Firebase/Crashlytics'
   pod 'Firebase/Analytics'
   inherit! :search_paths
   use_frameworks!
   pod "BlueStack-SDK" ,'4.2.6'

end
